<a href="https://colab.research.google.com/github/madhurisawana02/phonepay-data-analysis/blob/main/phonepay.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/PhonePe/pulse

Cloning into 'pulse'...
remote: Enumerating objects: 27741, done.
remote: Counting objects: 100% (2033/2033), done.
remote: Compressing objects: 100% (871/871), done.
remote: Total 27741 (delta 1943), reused 1162 (delta 1162), pack-reused 25708 (from 1)
Receiving objects: 100% (27741/27741), 27.47 MiB | 5.94 MiB/s, done.
Resolving deltas: 100% (14890/14890), done.

In [2]:
# table 1 aggregated transaction code
import pandas as pd
import json
import os
path = "/content/pulse/data/aggregated/transaction/country/india/state/"
agg_state_list=os.listdir(path)
clm = { 'State':[],'Year':[],'Quater':[],'Transaction_Type':[],'Transaction_count':[],'Transaction_amount':[]}
for i in agg_state_list:
    path_i = path+i+"/"
    agg_yr= os.listdir(path_i)
    for j in agg_yr:
        path_j = path_i+j+"/"
        agg_yr_list=os.listdir(path_j)
        for k in agg_yr_list:
            path_k=path_j+k
            data=open(path_k,'r')
            D=json.load(data)
            for z in D['data']['transactionData']:
                name=z['name']
                count=z['paymentInstruments'][0]['count']
                amount=z['paymentInstruments'][0]['amount']
                clm['Transaction_Type'].append(name)
                clm['Transaction_count'].append(count)
                clm['Transaction_amount'].append(amount)
                clm['State'].append(i)
                clm['Year'].append(j)
                clm['Quater'].append(int(k.strip('.json')))

                #successfullly created a dataFrama
                agg_trans= pd.DataFrame(clm)

In [ ]:
# table 1 aggregated transaction data
agg_trans

,State,Year,Quater,Transaction_Type,Transaction_count,Transaction_amount
0,delhi,2024,3,P2P,242375284,6.718651e+11
1,delhi,2024,3,Retail,552938672,2.233509e+11
2,delhi,2024,3,Utility,49397556,6.567883e+10
3,delhi,2024,1,P2P,196018058,6.007220e+11
4,delhi,2024,1,Retail,411667423,1.875081e+11
...,...,...,...,...,...,...
3666,jammu-&-kashmir,2026,1,Retail,93587796,4.776636e+10
3667,jammu-&-kashmir,2026,1,Utility,14375967,8.982353e+09
3668,jammu-&-kashmir,2026,2,P2P,55206052,1.365148e+11
3669,jammu-&-kashmir,2026,2,Retail,117475120,5.642193e+10
3670,jammu-&-kashmir,2026,2,Utility,15060953,1.009162e+10

In [4]:
# table 2 aggregated merchant code
import pandas as pd
import json
import os

# Explicitly set path and agg_mer_state_list for merchant data
path ="/content/pulse/data/aggregated/merchant/country/india/state/"
agg_mer_state_list=os.listdir(path)

clm = { 'State':[],'Year':[],'Quarter':[],'Registered_count':[]}
for i in agg_mer_state_list:   #level 1
    path_i = path+i+"/"
    agg_yr= os.listdir(path_i)
    for j in agg_yr:            #level 2
        path_j = path_i+j+"/"
        agg_yr_list=os.listdir(path_j)
        for k in agg_yr_list:     #level 3
            path_k=path_j+k
            data=open(path_k,'r')
            D=json.load(data)
            # Print the keys of D['data']['aggregated'] to inspect the structure
            # print(D['data']['aggregated'].keys()
            Registered_count= D['data']['aggregated']['registeredCount']
            clm['Registered_count'].append(Registered_count)
            clm['State'].append(i)
            clm['Year'].append(j)
            clm['Quarter'].append(int(k.strip('.json')))
#successfully completed dataframe
agg_merchants=pd.DataFrame(clm)

In [5]:
# table 2 aggregated merchant data
agg_merchants

           State  Year  Quarter  Registered_count
0      rajasthan  2022        4           2221707
1      rajasthan  2022        1           1863349
2      rajasthan  2022        3           2112900
3      rajasthan  2022        2           2003276
4      rajasthan  2018        4             45801
...          ...   ...      ...               ...
1173  tamil-nadu  2026        2           2358819
1174  tamil-nadu  2020        4            769374
1175  tamil-nadu  2020        1            484793
1176  tamil-nadu  2020        3            620844
1177  tamil-nadu  2020        2            516057

[1178 rows x 4 columns]

In [6]:
# table 3 aggregated user code
import pandas as pd
import json
import os

path = '/content/pulse/data/aggregated/user/country/india/state/'
agg_user=os.listdir(path)

clm = { 'State':[],'Year':[],'Quarter':[],'Registered_count':[]}
for i in agg_user:   #level 1
    path_i = path+i+"/"
    agg_yr= os.listdir(path_i)
    for j in agg_yr:            #level 2
        path_j = path_i+j+"/"
        agg_yr_list=os.listdir(path_j)
        for k in agg_yr_list:     #level 3
            path_k=path_j+k
            data=open(path_k,'r')
            D=json.load(data)
            # Print the keys of D['data']['aggregated'] to inspect the structure
            # print(D['data']['aggregated'].keys()
            Registered_count= D['data']['aggregated']['registeredCount']
            clm['Registered_count'].append(Registered_count)
            clm['State'].append(i)
            clm['Year'].append(j)
            clm['Quarter'].append(int(k.strip('.json')))
#successfully completed dataframe
aggregated_user=pd.DataFrame(clm)

In [7]:
# table 3 aggregated user data
aggregated_user

           State  Year  Quarter  Registered_count
0      rajasthan  2022        4          27182742
1      rajasthan  2022        1          23412998
2      rajasthan  2022        3          25962683
3      rajasthan  2022        2          24647652
4      rajasthan  2018        4           6407477
...          ...   ...      ...               ...
1219  tamil-nadu  2026        2          40264046
1220  tamil-nadu  2020        4          15495864
1221  tamil-nadu  2020        1          10970688
1222  tamil-nadu  2020        3          13765652
1223  tamil-nadu  2020        2          12255108

[1224 rows x 4 columns]

In [8]:
#table 4 map merchant table code
import pandas as pd
import json
import os

path = '/content/pulse/data/map/merchant/hover/country/india/'
map_merchant_yr=os.listdir(path)

clm = { 'State':[],'Year':[],'Quarter':[],'Registered_count':[]}
for i in map_merchant_yr:   #level 1
    path_i = path+i+"/"
    agg_yr= os.listdir(path_i)
    for k in agg_yr:
        path_k=path_i+k
        data = open(path_k,'r')
        D=json.load(data)
        for z in D['data']['hoverData'].items():
          state=z[0]
          Registered_count=z[1]['registeredCount']
          clm['State'].append(state)
          clm['Registered_count'].append(Registered_count)
          clm['Year'].append(i)
          clm['Quarter'].append(int(k.strip('.json')))

map_merchant=pd.DataFrame(clm)

In [9]:
#table 4 map_merchanr table data
map_merchant

                                   State  Year  Quarter  Registered_count
0              andaman & nicobar islands  2022        4              2740
1     dadra & nagar haveli & daman & diu  2022        4             17526
2                                    goa  2022        4             25200
3                                gujarat  2022        4           1624532
4                                haryana  2022        4           1231301
...                                  ...   ...      ...               ...
1173                          tamil nadu  2020        2            516057
1174                           telangana  2020        2            673726
1175                             tripura  2020        2              1741
1176                         uttarakhand  2020        2             52918
1177                         west bengal  2020        2            813620

[1178 rows x 4 columns]

In [10]:
# table 5 map transaction code
import pandas as pd
import json
import os

path = '/content/pulse/data/map/transaction/hover/country/india/'
map_transaction_yr=os.listdir(path)

clm = { 'State':[],'Year':[],'Quater':[],'Transaction_count':[],'Transaction_amount':[]}
for i in map_transaction_yr:   #level 1
    path_i = path+i+"/"
    map_yr= os.listdir(path_i)
    for k in map_yr:
        path_k=path_i+k
        data=open(path_k,'r')
        D=json.load(data)
        for z in D['data']['hoverDataList']:
          name=z['name']
          count=z['metric'][0]['count']
          amount=z['metric'][0]['amount']
          clm['State'].append(name)
          clm['Transaction_count'].append(count)
          clm['Transaction_amount'].append(amount)
          clm['Year'].append(i)
          clm['Quater'].append(int(k.strip('.json')))
          map_trasaction =pd.DataFrame(clm)

In [11]:
#table 5 map transaction table
map_trasaction

,State,Year,Quater,Transaction_count,Transaction_amount
0,andaman & nicobar islands,2022,4,2263155,4.313612e+09
1,andhra pradesh,2022,4,1030438279,2.028666e+12
2,arunachal pradesh,2022,4,7474281,1.469764e+10
3,bihar,2022,4,478561642,8.811473e+11
4,chandigarh,2022,4,9744704,1.272051e+10
...,...,...,...,...,...
1219,andhra pradesh,2020,2,176284886,3.806123e+11
1220,kerala,2020,2,15681152,2.292875e+10
1221,lakshadweep,2020,2,11502,3.091721e+07
1222,maharashtra,2020,2,180429884,2.813546e+11
1223,west bengal,2020,2,58763095,9.927838e+10

In [12]:
#table 6 map user code
import pandas as pd
import json
import os

path = '/content/pulse/data/map/user/hover/country/india/'
map_user=os.listdir(path)

clm = { 'State':[],'Year':[],'Quarter':[],'Registered_count':[]}
for i in map_user:   #level 1
    path_i = path+i+"/"
    map_yr= os.listdir(path_i)
    for k in map_yr:
      path_k=path_i+k
      data=open(path_k,'r')
      D=json.load(data)
      for z in D['data']['hoverData'].items():
        state=z[0]
        Registered_count=z[1]['registeredCount']
        clm['State'].append(state)
        clm['Registered_count'].append(Registered_count)
        clm['Year'].append(i)
        clm['Quarter'].append(int(k.strip('.json')))

#successfully completed dataframe
map_user=pd.DataFrame(clm)

In [13]:
#table 6 map user table data
map_user

                                   State  Year  Quarter  Registered_count
0              andaman & nicobar islands  2022        4            127606
1     dadra & nagar haveli & daman & diu  2022        4            431261
2                                    goa  2022        4            871837
3                                gujarat  2022        4          22608675
4                                haryana  2022        4          14567786
...                                  ...   ...      ...               ...
1219                             mizoram  2020        2             62148
1220                          puducherry  2020        2            249567
1221                              punjab  2020        2           4373346
1222                              sikkim  2020        2            127647
1223                       uttar pradesh  2020        2          23606047

[1224 rows x 4 columns]

In [50]:
# table 7 top transaction table code
import pandas as pd
import json
import os
path = "/content/pulse/data/top/transaction/country/india/state/"
top_state_list=os.listdir(path)
clm = { 'State':[],'Districts':[],'Year':[],'Quater':[],'Transaction_count':[],'Transaction_amount':[]}
for i in top_state_list:
    path_i = path+i+"/"
    top_state_yr= os.listdir(path_i)
    for j in top_state_yr:
      path_j = path_i+j+"/"
      top_yr_list=os.listdir(path_j)
      for k in top_yr_list:
        path_k=path_j+k
        data=open(path_k,'r')
        D=json.load(data)
        for z in D['data']['districts']:
          district_name=z['entityName']
          # Directly access type, count, and amount from z['metric']
          transaction_type=z['metric']['type']
          transaction_count=z['metric']['count']
          transaction_amount=z['metric']['amount']

          clm['State'].append(i)
          clm['Districts'].append(district_name)
          clm['Year'].append(j)
          clm['Quater'].append(int(k.strip('.json')))
          clm['Transaction_count'].append(transaction_count)
          clm['Transaction_amount'].append(transaction_amount)

top_transaction=pd.DataFrame(clm)

In [15]:
# table 7 top transaction table data
top_transaction

,State,Districts,Year,Quater,Transaction_count,Transaction_amount
0,rajasthan,jaipur district,2022,4,219882925,3.348410e+11
1,rajasthan,jodhpur district,2022,4,43593833,7.784396e+10
2,rajasthan,bhilwara district,2022,4,34654973,5.896074e+10
3,rajasthan,kota district,2022,4,33401300,4.448777e+10
4,rajasthan,sikar district,2022,4,32924291,6.550512e+10
...,...,...,...,...,...,...
10195,tamil-nadu,salem district,2020,2,2014950,3.731242e+09
10196,tamil-nadu,tiruppur district,2020,2,1886994,3.313600e+09
10197,tamil-nadu,madurai district,2020,2,1768928,3.391159e+09
10198,tamil-nadu,tiruchirappalli district,2020,2,1499472,2.871815e+09
10199,tamil-nadu,kancheepuram district,2020,2,1249794,1.936639e+09

In [54]:
#table 8 top merchant code
import pandas as pd
import os
import json

path = '/content/pulse/data/top/merchant/country/india/state/'
top_merchant_state=os.listdir(path)

clm= {'State':[],'Year':[],'Quarter':[],'Districts':[], 'Registered_users':[]}
for i in top_merchant_state:
  path_i= path+i+"/"
  top_merchant_yr= os.listdir(path_i)
  for j in top_merchant_yr:
    path_j= path_i+j+"/"
    for k in os.listdir(path_j):
      path_k=path_j+k
      data=open(path_k, 'r')
      D=json.load(data)
      for z in D['data']['districts']:
        Districts=z['name']
        Registered_users=z['registeredCount'] # Corrected key here

        clm['State'].append(i)
        clm['Year'].append(j)
        clm['Quarter'].append(int(k.strip('.json')))
        clm['Districts'].append(Districts)
        clm['Registered_users'].append(Registered_users)

top_merchant=pd.DataFrame(clm)

In [55]:
#table 8 top merchant data
top_merchant

           State  Year  Quarter                 Districts  Registered_users
0      rajasthan  2022        4           jaipur district            592486
1      rajasthan  2022        4             kota district            129971
2      rajasthan  2022        4          jodhpur district             99232
3      rajasthan  2022        4            sikar district             94473
4      rajasthan  2022        4         bhilwara district             86065
...          ...   ...      ...                       ...               ...
9727  tamil-nadu  2020        2         tiruppur district             20236
9728  tamil-nadu  2020        2  tiruchirappalli district             15789
9729  tamil-nadu  2020        2            salem district             13183
9730  tamil-nadu  2020        2            erode district             10698
9731  tamil-nadu  2020        2         dindigul district             10065

[9732 rows x 5 columns]

In [58]:
#table 9 top user code
import pandas as pd
import os
import json
path='/content/pulse/data/top/user/country/india/state/'
top_user_state=os.listdir(path)

clm= {'State':[],'Year':[],'Quarter':[],'Districts':[], 'Registered_users':[]}
for i in top_user_state:
  path_i= path+i+"/"
  top_user_yr= os.listdir(path_i)
  for j in top_user_yr:
    path_j= path_i+j+"/"
    top_user_list=os.listdir(path_j)
    for k in top_user_list:
      path_k=path_j+k
      data=open(path_k, 'r')
      D=json.load(data)
      for z in D['data']['districts']:
        Districts=z['name']
        Registered_users=z['registeredCount'] # Corrected key here

        clm['State'].append(i)
        clm['Year'].append(j)
        clm['Quarter'].append(int(k.strip('.json')))
        clm['Districts'].append(Districts)
        clm['Registered_users'].append(Registered_users)

top_user=pd.DataFrame(clm)

In [59]:
# table 9 top user data
top_user

            State  Year  Quarter                 Districts  Registered_users
0       rajasthan  2022        4           jaipur district           5382340
1       rajasthan  2022        4          jodhpur district           1471224
2       rajasthan  2022        4            sikar district           1157670
3       rajasthan  2022        4             kota district           1004151
4       rajasthan  2022        4         bhilwara district            947679
...           ...   ...      ...                       ...               ...
10195  tamil-nadu  2020        2            salem district            506118
10196  tamil-nadu  2020        2          madurai district            457233
10197  tamil-nadu  2020        2      krishnagiri district            436314
10198  tamil-nadu  2020        2  tiruchirappalli district            380221
10199  tamil-nadu  2020        2     kancheepuram district            323778

[10200 rows x 5 columns]

In [60]:
len(top_user)

10200